export const dopingExperience = {
  slug: 'doping-control', order: 2, visible: true, type: 'biological',
  title: { en: 'Quality Control Intern', tr: 'Kalite Kontrol Stajyeri' },
  institution: { en: 'Hacettepe University Turkish Doping Control Center', tr: 'Hacettepe Üniversitesi Türkiye Doping Kontrol Merkezi' },
  date: { en: 'Jul — Aug 2025', tr: 'Tem — Ağu 2025' },
  summary: { en: 'A 20-day placement following anti-doping sample preparation, screening and instrument-facing workflows across LC-MS/MS, GC-MS/MS, LC-HRMS and GC-C-IRMS.', tr: 'LC-MS/MS, GC-MS/MS, LC-HRMS ve GC-C-IRMS boyunca doping kontrol numune hazırlama, tarama ve cihazla ilişkili iş akışlarını izlediğim 20 günlük staj.' },
  role: { en: 'I worked through wet-chemistry and sample-preparation stages and learned how those preparations feed instrument sequences, internal-standard calibration, confirmation and reporting. Public content intentionally avoids reproducing laboratory SOPs step-by-step.', tr: 'Yaş kimya ve numune hazırlama aşamalarında çalıştım; bu hazırlıkların cihaz sequence’larına, internal-standard kalibrasyonuna, doğrulamaya ve raporlamaya nasıl bağlandığını öğrendim. Kamuya açık içerikte laboratuvar SOP’lerini adım adım yeniden yayımlamıyorum.' },
  workflow: ['Sample reception', 'SG / pH checks', 'Aliquot & preparation', 'Extraction / hydrolysis', 'LC- or GC-based analysis', 'Confirmation & reporting'],
  methods: ['LC-MS/MS', 'GC-MS/MS', 'LC-HRMS', 'GC-C-IRMS', 'HPLC', 'SPE', 'MSTFA derivatization', 'Internal-standard calibration'],
  sections: [
    { eyebrow: '01 · SAMPLE INTEGRITY', title: { en: 'The workflow starts before the mass spectrometer', tr: 'İş akışı kütle spektrometresinden önce başlar' }, paragraphs: { en: ['The report begins with sample-reception controls such as specific gravity and pH. These simple measurements are part of a larger quality system: temperature, calibration checks and repeatable handling establish whether a sample can move forward into screening.', 'Seeing this front end made the analytical chain clearer to me. A high-performance detector cannot rescue poor sample handling; trace analysis depends on disciplined preparation and controls from the first tube onward.'], tr: ['Raporum numune kabulünün özgül ağırlık ve pH gibi kontrollerle başladığını gösteriyor. Bu basit ölçümler daha büyük bir kalite sisteminin parçası: sıcaklık, kalibrasyon kontrolleri ve tekrarlanabilir numune işlemleri numunenin taramaya ilerleyip ilerleyemeyeceğini belirliyor.', 'Bu başlangıç aşamasını görmek analitik zinciri benim için daha anlaşılır hale getirdi. Yüksek performanslı bir dedektör kötü numune işlemeyi telafi edemez; iz düzey analiz ilk tüpten itibaren disiplinli hazırlık ve kontrollere bağlıdır.'] }, image: '/images/experience/doping/ph-meter.webp', caption: { en: 'pH measurement setup documented in my internship report.', tr: 'Staj raporumda belgelenen pH ölçüm düzeneği.' }, art: 'doping' },
    { eyebrow: '02 · TARGETED PREPARATION', title: { en: 'Different analyte groups require different preparation logic', tr: 'Farklı analit grupları farklı hazırlama mantığı gerektirir' }, paragraphs: { en: ['Urine samples were divided into workflows targeting different prohibited-substance groups. Depending on the method, preparation could include enzymatic hydrolysis, liquid extraction, SPE or derivatization before the sample was transferred to LC-MS/MS or GC-MS/MS.', 'The small-peptide workflow in the report, for example, uses solid-phase extraction before LC-MS/MS. GC-based steroid and stimulant workflows rely on derivatization to make suitable analytes more compatible with gas chromatography. I learned to see sample preparation as part of the selectivity of the method—not a separate housekeeping step.'], tr: ['İdrar numuneleri farklı yasaklı madde gruplarını hedefleyen iş akışlarına ayrılıyordu. Yönteme göre hazırlık; enzimatik hidroliz, sıvı ekstraksiyon, SPE veya türevlendirme içerebiliyor ve ardından numune LC-MS/MS ya da GC-MS/MS analizine geçiyordu.', 'Rapordaki küçük peptit iş akışında örneğin LC-MS/MS öncesi katı faz ekstraksiyonu kullanılıyor. GC tabanlı steroid ve stimülan iş akışlarında ise uygun analitleri gaz kromatografisine elverişli hale getirmek için türevlendirme önemli. Numune hazırlamayı yöntemin seçiciliğinin bir parçası olarak görmeyi öğrendim.'] }, image: '/images/experience/doping/sample-preparation.webp', caption: { en: 'Sample-preparation apparatus photographed during the internship.', tr: 'Staj sırasında fotoğraflanan numune hazırlama düzeneği.' }, art: 'sample' },
    { eyebrow: '03 · MASS SPECTROMETRY', title: { en: 'LC, GC, high resolution and isotope-ratio questions', tr: 'LC, GC, yüksek çözünürlük ve izotop oranı soruları' }, paragraphs: { en: ['LC-MS/MS and LC-HRMS were discussed for compounds that are non-volatile or better handled in liquid-phase workflows, while GC-MS/MS supported workflows involving volatile or derivatized compounds. The placement also introduced GC-C-IRMS, where the analytical question is not simply “is this steroid present?” but whether its carbon-isotope signature is consistent with an endogenous or synthetic source.', 'Following these platforms side by side was valuable because the instrument choice became connected to chemical properties and the question being asked, rather than being a list of acronyms.'], tr: ['LC-MS/MS ve LC-HRMS; uçucu olmayan veya sıvı faz iş akışlarına daha uygun bileşiklerde ele alınırken, GC-MS/MS uçucu ya da türevlendirilmiş bileşiklerin iş akışlarında kullanılıyordu. Staj aynı zamanda GC-C-IRMS ile tanıştırdı; burada analitik soru yalnızca “bu steroid var mı?” değil, karbon izotop imzasının endojen veya sentetik kökenle uyumlu olup olmadığıdır.', 'Bu platformları yan yana görmek, cihaz seçimini kısaltmalar listesinden çıkarıp bileşiğin kimyasal özelliklerine ve sorulan analitik soruya bağlamamı sağladı.'] }, image: '/images/experience/doping/lc-ms.webp', caption: { en: 'LC–MS system photographed during my internship.', tr: 'Stajım sırasında fotoğraflanan LC–MS sistemi.' }, art: 'ms' },
    { eyebrow: '04 · QUALITY SYSTEM', title: { en: 'Calibration, controls and confirmation are part of the result', tr: 'Kalibrasyon, kontroller ve doğrulama sonucun parçasıdır' }, paragraphs: { en: ['The report uses a structured vocabulary for negative controls, positive controls, calibration levels, quality controls and internal standards. That framework showed how a trace-level result is supported by evidence around the sample, not just by one instrument peak.', 'Across the placement I followed the larger sequence from reception and preparation through screening, internal-standard calibration, confirmation and result reporting. This quality-control mindset is one of the most transferable parts of the experience.'], tr: ['Raporda negatif kontroller, pozitif kontroller, kalibrasyon seviyeleri, kalite kontrol numuneleri ve internal standardlar için yapılandırılmış bir sistem bulunuyor. Bu çerçeve, iz düzey bir sonucun yalnızca tek bir cihaz pikine değil, numunenin çevresindeki kontrol kanıtlarına dayandığını gösterdi.', 'Staj boyunca numune kabulünden hazırlama ve taramaya, internal-standard kalibrasyonundan doğrulama ve sonuç raporlamaya uzanan büyük diziyi takip ettim. Kalite kontrol bakışı bu deneyimin en aktarılabilir kazanımlarından biri oldu.'] }, image: '/images/experience/doping/sample-rack.webp', caption: { en: 'Prepared sample rack documented in the internship report.', tr: 'Staj raporunda belgelenen hazırlanmış numune rack’i.' }, art: 'qc' }
  ]
}
