export const realPhotos = {
  labScientist: 'https://upload.wikimedia.org/wikipedia/commons/0/01/Scientists_are_working_in_the_lab.1.jpg',
  lcms: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Liquid_chromatograph_with_mass_spectrometer%2C_in_CAFIA_laboratory%2C_Czech_Republic.png/1280px-Liquid_chromatograph_with_mass_spectrometer%2C_in_CAFIA_laboratory%2C_Czech_Republic.png',
  gcms: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/GCMS_Instrument.jpg/1280px-GCMS_Instrument.jpg',
  qtof: 'https://upload.wikimedia.org/wikipedia/commons/9/9c/Liquid_chromatograph_with_a_mass_spectrometer_operating_on_the_principle_of_flight_time_in_combination_with_a_quadrupole_analyzer_%28qTOF%29_in_CAFIA_laboratory%2C_Czech_Republic.jpg',
  irms: 'https://upload.wikimedia.org/wikipedia/commons/b/b5/Isotope_Ratio_Mass_Spectrometer_%2808010617%29_%2845919100874%29.jpg',
  electrophoresis: 'https://upload.wikimedia.org/wikipedia/commons/0/07/Electrophoresis_equipment.jpg',
  icpmsPrep: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Scientist_prepares_samples_for_the_Inductively_Couples_Plasma_Mass_Spectroscopy_%28ICP-MS%29_analysis.jpg/1280px-Scientist_prepares_samples_for_the_Inductively_Couples_Plasma_Mass_Spectroscopy_%28ICP-MS%29_analysis.jpg',
  xrf: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Fischer_XRF_machine.jpg/1280px-Fischer_XRF_machine.jpg',
  icpOes: 'https://upload.wikimedia.org/wikipedia/commons/d/df/Spectrometer_ICP-OES.jpg',
  tga: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Thermogravimetric_analyser.jpg/1280px-Thermogravimetric_analyser.jpg',
  coal: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/CSIRO_ScienceImage_11364_Coal_sample.jpg/1280px-CSIRO_ScienceImage_11364_Coal_sample.jpg',
  labNotebook: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Lab_Notebook.jpg/1280px-Lab_Notebook.jpg',
  patentApplication: 'https://upload.wikimedia.org/wikipedia/commons/4/4d/Patent_application.jpg',
}

export const imageCredits = {
  [realPhotos.labScientist]: {
    author: 'Yakuzakorat',
    license: 'CC BY 4.0',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Scientists_are_working_in_the_lab.1.jpg',
    licenseUrl: 'https://creativecommons.org/licenses/by/4.0/',
  },
  [realPhotos.lcms]: {
    author: 'Sarka Na kopci',
    institution: 'CAFIA laboratory, Czech Republic',
    license: 'CC BY-SA 4.0',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Liquid_chromatograph_with_mass_spectrometer,_in_CAFIA_laboratory,_Czech_Republic.png',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
  },
  [realPhotos.gcms]: {
    author: 'Cyberwork 95',
    license: 'CC BY-SA 4.0',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:GCMS_Instrument.jpg',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
  },
  [realPhotos.qtof]: {
    author: 'Sarka Na kopci',
    institution: 'CAFIA laboratory, Czech Republic',
    license: 'CC BY-SA 4.0',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Liquid_chromatograph_with_a_mass_spectrometer_operating_on_the_principle_of_flight_time_in_combination_with_a_quadrupole_analyzer_(qTOF)_in_CAFIA_laboratory,_Czech_Republic.jpg',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
  },
  [realPhotos.irms]: {
    author: 'IAEA Imagebank / Dean Calma',
    institution: 'International Atomic Energy Agency',
    license: 'CC BY 2.0',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Isotope_Ratio_Mass_Spectrometer_(08010617)_(45919100874).jpg',
    licenseUrl: 'https://creativecommons.org/licenses/by/2.0/',
  },
  [realPhotos.electrophoresis]: {
    author: 'NIH / NIAMS',
    institution: 'U.S. National Institutes of Health',
    license: 'Public domain',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Electrophoresis_equipment.jpg',
    licenseUrl: 'https://commons.wikimedia.org/wiki/Commons:Copyright_rules_by_territory/United_States#Works_by_the_US_Federal_Government',
  },
  [realPhotos.icpmsPrep]: {
    author: 'Kevin Tong',
    institution: 'UC Davis College of Engineering',
    license: 'CC BY 2.0',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Scientist_prepares_samples_for_the_Inductively_Couples_Plasma_Mass_Spectroscopy_(ICP-MS)_analysis.jpg',
    licenseUrl: 'https://creativecommons.org/licenses/by/2.0/',
  },
  [realPhotos.xrf]: {
    author: 'Encik Tekateki',
    license: 'CC BY-SA 4.0',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Fischer_XRF_machine.jpg',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
  },
  [realPhotos.icpOes]: {
    author: 'Karel',
    license: 'Public domain',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Spectrometer_ICP-OES.jpg',
    licenseUrl: 'https://commons.wikimedia.org/wiki/Commons:Public_domain',
  },
  [realPhotos.tga]: {
    author: 'Luigi Chiesa',
    license: 'CC BY 3.0',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Thermogravimetric_analyser.jpg',
    licenseUrl: 'https://creativecommons.org/licenses/by/3.0/',
  },
  [realPhotos.coal]: {
    author: 'Nick Pitsas / CSIRO',
    institution: 'CSIRO',
    license: 'CC BY 3.0',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:CSIRO_ScienceImage_11364_Coal_sample.jpg',
    licenseUrl: 'https://creativecommons.org/licenses/by/3.0/',
  },
  [realPhotos.labNotebook]: {
    author: 'Katherine Stember',
    license: 'CC BY 4.0',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Lab_Notebook.jpg',
    licenseUrl: 'https://creativecommons.org/licenses/by/4.0/',
  },
  [realPhotos.patentApplication]: {
    author: 'U.S. Patent Office / Swartwout',
    institution: 'United States Patent and Trademark Office',
    license: 'Public domain',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Patent_application.jpg',
    licenseUrl: 'https://commons.wikimedia.org/wiki/Commons:Copyright_rules_by_territory/United_States#Works_by_the_US_Federal_Government',
  },
}
